# Nathanael Gandhi | github.com/NathanaelGandhi

name: 'Label issues and PRs'
on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited, auto_merge_enabled]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  call-reusable:
    uses: NathanaelGandhi/labeler-reusable-workflow/.github/workflows/labeler-reusable.yaml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      caller_token: ${{ secrets.GITHUB_TOKEN }}
