# Nathanael Gandhi | github.com/NathanaelGandhi

# NOTE: This makes a commit to your default branch with [skip ci]

name: 'Release Caller'
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-conventional-changelog:
    uses: NathanaelGandhi/release-reusable-workflow/.github/workflows/release-reusable.yaml@main
    secrets:
      caller_token: ${{ secrets.GITHUB_TOKEN }}
