# Nathanael Gandhi | github.com/NathanaelGandhi

name: 'Release Caller'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  clang-format-check:
    uses: NathanaelGandhi/reusable-workflows/.github/workflows/release-reusable.yaml@main
    secrets: inherit
